apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-ui
  labels:
    app: ecommerce-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecommerce-ui
  template:
    metadata:
      labels:
        app: ecommerce-ui
        version: v1
    spec:
      containers:
      - name: ecommerce-ui
        image: rslim087/ecommerce-ui:latest
        ports:
        - containerPort: 4000
          name: http
        env:
        - name: REACT_APP_PROFILE_API_HOST
          value: "profile-management-staging"
        - name: REACT_APP_PROFILE_API_PORT
          value: "3003"
        - name: REACT_APP_PRODUCT_API_HOST
          value: "product-catalog-staging"
        - name: REACT_APP_PRODUCT_API_PORT
          value: "3001"
        - name: REACT_APP_INVENTORY_API_HOST
          value: "product-inventory-staging"
        - name: REACT_APP_INVENTORY_API_PORT
          value: "3002"
        - name: REACT_APP_ORDER_API_HOST
          value: "order-management-staging"
        - name: REACT_APP_ORDER_API_PORT
          value: "9090"
        - name: REACT_APP_SHIPPING_API_HOST
          value: "shipping-and-handling-staging"
        - name: REACT_APP_SHIPPING_API_PORT
          value: "8080"
        - name: REACT_APP_CONTACT_API_HOST
          value: "contact-support-team-staging"
        - name: REACT_APP_CONTACT_API_PORT
          value: "8000"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-ui
  labels:
    app: ecommerce-ui
spec:
  ports:
  - port: 4000
    targetPort: 4000
    name: http
  selector:
    app: ecommerce-ui
