apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-inventory
      version: v1
  template:
    metadata:
      labels:
        app: product-inventory
        version: v1
    spec:
      containers:
      - name: product-inventory
        image: rslim087/product-inventory:1.0.0
        ports:
        - containerPort: 3002
---
apiVersion: v1
kind: Service
metadata:
  name: product-inventory
spec:
  ports:
  - port: 3002
    name: http
  selector:
    app: product-inventory
