apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: ecommerce-ui
spec:
  gateways:
  - ecommerce-gateway-staging
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: ecommerce-ui-staging
        port:
          number: 4000
