apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecommerce-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://github.com/YOUR-USERNAME/istio-eks-terraform-gitops.git
    targetRevision: HEAD
    path: k8s-manifests/staging
  
  destination:
    server: https://kubernetes.default.svc
    namespace: ecommerce-staging
  
  syncPolicy:
    automated:
      prune: true        # Remove recursos deletados do Git
      selfHeal: true     # Corrige drift automático
      allowEmpty: false  # Não permite deploy de diretório vazio
    
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  revisionHistoryLimit: 10
  
  # Notificações e health checks
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas  # Ignora mudanças de HPA
